version: "3.8"

services:
  dex:
    image: dexidp/dex:v2.26.0
    networks:
      ldapnet:
    ports:
      - 5556:5556
    volumes:
      - ./config-ldap.yml:/tmp/dex-config/config-ldap.yml
      - ./dex.db:/data/dex.db
    command: ["serve", "/tmp/dex-config/config-ldap.yml"]

  ldap:
    build:
      dockerfile: ./Dockerfile
      context: .
    command: ["--copy-service", "--loglevel", "debug"]
    networks:
      ldapnet:
    volumes:
      - /var/lib/ldap
      - /etc/ldap/slap.d
      - /container/service/slapd/assets/certs
    ports:
      - 389:389
    domainname: "linnify.org"
    hostname: "linnify.org"
    tty: true
    stdin_open: true

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    networks:
      ldapnet:
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ldap
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - 8080:80
    depends_on:
      - ldap

networks:
  ldapnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.0.0/16
          gateway: 172.31.0.1
