version: "3.8"

services:
  dex:
    image: dexidp/dex:v2.26.0
    ports:
      - 5556:5556
    volumes:
      - ./config-ldap.yml:/tmp/dex-config/config-ldap.yml
      - ./dex.db:/data/dex.db
    command: ["serve", "/tmp/dex-config/config-ldap.yml"]

  api:
    build:
      dockerfile: ./Dockerfile
      context: ./backend
    env_file:
      - ./backend/.env
    ports:
      - 8000:8000

  web:
    build:
      dockerfile: ./Dockerfile
      context: ./web
    ports:
      - 3000:3000

  ldap:
    build:
      dockerfile: ./Dockerfile
      context: ./ldap
    command: ["--copy-service", "--loglevel", "debug"]
    volumes:
      - /var/lib/ldap
      - /etc/ldap/slap.d
      - /container/service/slapd/assets/certs
    ports:
      - 389:389
    domainname: "linnify.org"
    hostname: "linnify.org"
    tty: true
    stdin_open: true

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ldap
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - 8080:80
    depends_on:
      - ldap
